version: '3'

services:
  www:
    build: .
    volumes:
      - "../:/var/www/html" # sync the current dir on local machine to the dir of container
    depends_on:
      - db
    networks:
      - default
    ports:
      - '80:80'

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_PASSWORD=root 
      - MYSQL_DATABASE=teste_nsolucoes
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d # this is how we persist a sql db even when container stops
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      ports:
          - 8081:80
      environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
volumes:
    persistent:

# version: '3'
# services:
#   db: 
#     image: mysql:latest
#     environment:
#       - MYSQL_DATABASE=teste_nsolucoes
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=root # this should live in a env var
#       - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
#     volumes:
#       - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
#   www:
#     image: php:apache
#     volumes:
#       - "./:/var/www/html" # sync the current dir on local machine to the dir of container
#     ports:
#       - 80:80
#       - 443:443 # for future ssl traffic
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - 8001:80
#     environment:
#       - PMA_HOST=db
#       - PMA_PORT=3306




# version: '3.7'
# services:

#   www:
#     image: 'php:apache'
#     container_name: phpApache
#     volumes: 
#       - "./:/var/www/html"
#     ports:
#       - "80:80" 

#   db:
#     container_name: mysqlNsolucoes
#     image: mysql:latest
#     environment:
#     - MYSQL_DATABATE=teste_nsolucoes
#     - MYSQL_USER=root
#     - MYSQL_ALLOW_EMPTY_PASS=1

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: myadmin-nsolucoes
#     ports:
#       - 8081:80
#     environment:
#       - PMA_HOST=db
#       - PMA_PORT=3306
#     depends_on:
#       - db